---
seed: 1984

num_workers: 4
experiment_name: "2020-12-02"
val_split: 0.1

model:
  type: timm.create_model
  model_name: tf_efficientnet_b3_ns
  num_classes: 4
  pretrained: True

trainer:
  type: pytorch_lightning.Trainer
  gpus: 4
  max_epochs: 30
  distributed_backend: ddp
  progress_bar_refresh_rate: 1
  benchmark: True
  precision: 16
  gradient_clip_val: 5.0
  num_sanity_val_steps: 1
  sync_batchnorm: True

scheduler:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2

train_parameters:
  batch_size: 16

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  filepath: "2020-12-02"
  monitor: val_loss
  verbose: True
  mode: min
  save_top_k: -1

val_parameters:
  batch_size: 64

optimizer:
  type: torch.optim.SGD
  momentum: 0.9
  lr: 0.1

loss:
  type: torch.nn.CrossEntropyLoss

train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
        always_apply: False
        height: 400
        width: 400
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
        always_apply: False
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.ColorJitter
        always_apply: False
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.4
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Blur
        always_apply: False
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.ToGray
        always_apply: False
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.CenterCrop
        always_apply: False
        height: 400
        width: 400
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

test_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.CenterCrop
        always_apply: False
        height: 400
        width: 400
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225
